### ISSUE TITLE
Apache Basic authorization

### ISSUE THREAD

**Issue by wkrawczak** [rozpuszczalny/vscode-redmine#10]
Hi,

A small suggestion - would it be possible to add the option for apache basic authorization (htaccess/htpasswd authorization)?

Thanks,

Wojtek

**Comment by rozpuszczalny** [comment]
Hi,
Thanks for suggestion. If I understood correctly, you've got redmine behind apache proxy, right? If so, will it be enough to add config property to add Authorization/custom headers, which will be added to every request?

**Comment by wkrawczak** [comment]
Yes, that would be perfect. Thank you for getting back.

**Comment by rozpuszczalny** [comment]
Solved by 585a78a98fb69b66f8512fa106bade40841526d1.
Adding `Authorization` header is done by setting `redmine.authorization`.
Tested with redmine behind nginx secured by basic auth and everything went just fine.
Feel free to reopen this issue, if it doesn't work as expected.

**Comment by wkrawczak** [comment]
Brilliant, thank you. :)

**Comment by saiballo** [comment]
I'm sorry but not understand the additionalHeaders object.

In my settings.json I add:

"redmine.additionalHeaders": {
        "authorization" : "Basic [base64 encoded username:password]"
    }

but it does not work. Where I fail?

thank you

**Comment by rozpuszczalny** [comment]
Hey @saiballo, thanks for asking! It appears that `additionalHeaders` and `rejectUnauthorized` options are not taken into account by the extension at all, which is obviously a bug. I've created an issue for that: #37. If you have further questions or doubts in this matter, please continue the discussion here.

Once again, thanks for spotting and making me aware ;)

**Comment by saiballo** [comment]
You are welcome! I'm glad to help you in working to this extension :-)

thank you

**Comment by saiballo** [comment]
I'm really really sorry... it was my fault!!!! Plugins finally works!! Good job!
