### ISSUE TITLE
Issues panel filtered

### ISSUE THREAD

**Issue by Sendery** [rozpuszczalny/vscode-redmine#11]
It will be great to have a panel where the open/new/inprogress  issues (or a custom filter) assigned to me will be listed

Something like this:
http://www.redmine.org/attachments/download/490/mylyn-task-list.png

But locatend the same way as the outline section

**Comment by rozpuszczalny** [comment]
I've to admit, it's quite intresting feature to have. Definitely adding this to To Do in New features.
