### ISSUE TITLE
Project name setting doesn't work

### ISSUE THREAD

**Issue by rooc** [rozpuszczalny/vscode-redmine#15]
"List open issues assigned to me" command shows issues from all projects, not from specified one.

**Comment by rozpuszczalny** [comment]
> `redmine.projectName`: If set, this will be the project, to which new issue will be created.

This setting is used in "Create new issue" command. Currently it's not implemented to do more scoped queries like list issues assigned to me in specified project.

**Comment by rooc** [comment]
thank you, but specific repo belongs to specific project in redmine, so showing me all my tickets doesn't make sens and difficult to find current project issues.

**Comment by rozpuszczalny** [comment]
Indeed, that's why I'm working on a concept of custom queries. Also I'll make few predefined queries, as requested. Query that you mentioned will definitely be there.
