### ISSUE TITLE
Add a sidebar

### ISSUE THREAD

**Issue by rogermartensson** [rozpuszczalny/vscode-redmine#17]
Just putting it out here if you find the time and knowledge to implement it.

Implement a sidebar for showing issues and other information that works well with a sidebar.

**Comment by rozpuszczalny** [comment]
This feature is the same as #11. I've began some work on this, when I'll have more free time, I'll finish it ;)
![redmine_issues_sidebar](https://user-images.githubusercontent.com/7627635/54225428-efabbb00-44fb-11e9-89fd-b29d4fc22c8d.png)
