### ISSUE TITLE
Create New Issue takes me to a 404 page

### ISSUE THREAD

**Issue by ericblade** [rozpuszczalny/vscode-redmine#20]
I seem to have configured everything properly, as all of the other features work, but when I hit Redmine: Create Issue, I get taken to https://tracker.randomstreasures.com/projects/Treasure Finder/issues/new .. which is a 404.

(update: it turns out the project name should be "treasure-finder", but using "Treasure Finder" worked fine for all the other functions)

**Comment by rozpuszczalny** [comment]
Yes, whole point of `projectName` is to have identifier value, not project name itself. It is mentioned in the config guide:

> NOTE: this is an identifier of project, not display name of the project

I should deprecate this option in the next release with something like `projectIdentifier`.

Nevertheless, glad you figured it out! :)
