### ISSUE TITLE
Plugin functionality not available due to error

### ISSUE THREAD

**Issue by n158** [rozpuszczalny/vscode-redmine#22]
Settings and error screens provided. Tried to access "List open issues assigned to me" and got error. Same error when try to open issue under cursor. Redmine version v3.4.10. Any help is appreciated.

![image](https://user-images.githubusercontent.com/18001539/75013288-9c244a00-548c-11ea-9f91-73b3edc9afcd.png)
![image](https://user-images.githubusercontent.com/18001539/75013587-3dab9b80-548d-11ea-8949-16cab74b5ada.png)

**Comment by rozpuszczalny** [comment]
You should ommit "https://" in server URL. Also, project name shouldn't be whole project URL, it should be only name after "/projects/". Regarding server URL, it is confusing and will be changed in v1

**Comment by rozpuszczalny** [comment]
Feel free to reopen this issue, if it still occurs.
