### ISSUE TITLE
issue description null problem

### ISSUE THREAD

**Issue by MS-Song** [rozpuszczalny/vscode-redmine#23]
hi.

Redmine issue description is null. 

find error. 

issue.description.split("\n") <== null....

I fix it. switch = "".

fix please. 

    promise.then((issues) => {
            vscode.window.showQuickPick(issues.issues.map((issue) => {
                return {
                    "label": `[${issue.tracker.name}] (${issue.status.name}) ${issue.subject} by ${issue.author.name}`,
                    //"description": issue.description.split("\n").join(" ").split("\r").join("") ,
                    "description": "" ,
                    "detail": `Issue #${issue.id} assigned to ${issue.assigned_to ? issue.assigned_to.name : "no one"}`,
                    "fullIssue": issue
                };
            })).then((issue) => {

**Comment by rozpuszczalny** [comment]
Hi, thanks for spotting that!

Proper fix should check if `issue.description` is defined, then do all split stuff, like so:

```js
(issue.description || "").split("\n").join(" ").split("\r").join("")
```

I'll introduce a fix once I'll find some time.

**Comment by MS-Song** [comment]
Thanks. 
I'm fork your repository. after fix  pull request to you someday. (Studying VScode plugin develop..)
