### ISSUE TITLE
Not resolving some dns...

### ISSUE THREAD

**Issue by Sendery** [rozpuszczalny/vscode-redmine#4]
Firts of all thanks for developing this great tool.

While testing differents configurations I had try statics IPs for the "redmine.serverUrl" field of my redmine server and it works well.
But when using AWS IPs such us "ec2-XX-XX-XXX-XX.eu-west-1.compute.amazonaws.com" it does not resolve the properly the ip.

Configuration:
redmine.serverUrl="ec2-XX-XX-XXX-XX.eu-west-1.compute.amazonaws.com",

Could it be that for the "-" or "." or the long url such as those it will not work?

Thank you

**Comment by rozpuszczalny** [comment]
Hi,
url isn't the case. Just tried similar url like `redmine-with-dash-and.with.many.dots.tomaszdomanski.com`, which is longer that url provided by you, and it works.
Entering your url works in browser? Maybe you haven't set properly `redmine.serverIsSsl` or something like that. Also let me know if problem still occurs, I'll try to dig deeper, if it's still not working.

**Comment by rozpuszczalny** [comment]
I'm closing this issue due to no response. Feel free to reopen this issue, if it still occurs.
