### ISSUE TITLE
my redmine cant display the prjoject issues which i want to see in vscode

### ISSUE THREAD

**Issue by luqiudi** [rozpuszczalny/vscode-redmine#54]
**IMPORTANT**

If you want to create a feature request, do it through [Discussions tab](https://github.com/rozpuszczalny/vscode-redmine/discussions).
Your issue will be converted into the discussion, if it is a feature request.

If the bug is related to the security issue, do NOT create an issue. Email github@rozpuszczalny.com instead.

**Describe the bug**

i've set  the project id ,bug vscode-redmine also display all the issues in all projects,
what shoud i set?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by rozpuszczalny** [comment]
Hi, thanks for the report!

Unfortunately, that's how `vscode-redmine` works - it always shows issues for all projects. If you feel like you'd benefit from such a feature, feel free to create a new discussion in the [discussions tab](https://github.com/rozpuszczalny/vscode-redmine/discussions)

Best,
Tomek
